### ISSUE TITLE
3rd party references and papers

### ISSUE THREAD

**Issue by ghost** [solvespace/solvespace-web#1]
It would be good collect 3rd party papers that discribe SolveSpace on some of this pages:
- http://solvespace.com/tutorial.pl
- http://solvespace.com/reference.pl
### REFERENCES

(part 1)
- https://www.cse.iitb.ac.in/~ranade/ihci2013.pdf
- http://www.cms.bgu.tum.de/publications/reports/2016_Kohl_Singer.pdf
- http://aralex.ro/download/TutorialSolveSpace.pdf
- http://inpressco.com/wp-content/uploads/2016/10/Paper521784-1791.pdf
- http://me.eng.sunysb.edu/software/images/DETC2014-35235.pdf
- http://class.skycluster.net/_media/documentation/archive/2016/files/2016_iu4_conf_gormakova.pdf
- http://patentimages.storage.googleapis.com/pdfs/USD704059.pdf
- http://specialchem4bio.com/~/media/documents/articles/2016/09/cad%20market%20share%20and%20size%20emerging%20trends%20analysis%20overview%20and%20outlook%20growth%20and%20segment%20forecasts%20to%202020pdf.pdf
- http://computer.razaviedu.ir/index.php/joomla-pages-2/2016-08-09-11-50-11/item/download/602_858ddf7fb5dd9b1dbb7316a1bb33139c
- http://www.researchandmarkets.com/reports/3428013/cad-market-in-the-aerospace-and-defense-industry.pdf
  - http://www.researchandmarkets.com/reports/3339668/cad-market-in-italy-2015-2019.pdf
- https://pdf.marketpublishers.com/inf_res/global-cad-market-in-automotive-industry-2016-2020.pdf
- http://newtech.educom.ru/files/pdf/2016-02-08_02-18-46-66.pdf
- https://www.sculpteo.com/static/0.30.0-112/download/ebooks/Sculpteo_ultimate_guide_laser_cutting.pdf
- http://ab.org.tr/ab14/bildiri/226.pdf
- http://www.ngon-paradise.com/wiki/doku.php?do=export_pdf&id=fao:cnc-3dprinting-softwares
- http://docs.neu.edu.tr/library/6369034357.pdf
- http://www.eltech.ru/assets/files/abiturient/dovuzovskaya-podgotovka/konf-2014/materialy-konfer-2014.pdf
- http://iu4.ru/konf/2016_ts/all_sbornik.pdf
- http://chap.sch.ir/sites/default/files/lbooks/95-96/137/C210203.pdf

**Comment by ghost** [comment]
### REFERENCES

(part 2)
- http://class.skycluster.net/_media/documentation/archive/2016/files/2016_iu4_conf_kirilenko.pdf
- http://class.skycluster.net/_media/documentation/archive/2016/files/2016_iu4_conf_lapshinov.pdf
- http://oa50u9.rg.ro/6-pJ
- ...

**Comment by whitequark** [comment]
I have looked through every link you've listed. These are just some junk PDFs that happen to mention the word "SolveSpace". It is not useful to anyone. Please do not waste my time like this ever again. I am fully capable of running a Google search on my own.
