### ISSUE TITLE
Add a page "Drawing"

### ISSUE THREAD

**Issue by BPLRFE** [solvespace/solvespace-web#10]
I would add a page "Drawing" for tips on exporting to other software for producing technical 2D drawings.
Tips would include exporting to:
> Libre Office/Open Office draw (as svg)
> Inkscape (as svg)
> LibreCAD (as DXF)
> Draftsight (as DXF)

**Comment by ruevs** [comment]
In my opinion this is not a necessary part for solvespace.com.
Anyone who has discovered SolveSpace and knows how to use some of the mentioned programs will know what to do and will not need an explanation.
The export capabilities of SolveSpace are documented in the "Export section in the reference manual.

@phkahler should I close this?
