### ISSUE TITLE
Incorrect time stamps for messages inside topics

### ISSUE THREAD

**Issue by ghost** [solvespace/solvespace-web#13]
If look in topics list, latest active topic dated on `Fri Oct 27 2017, 18:16:46`
* Latest active topic on the topics list:
  > <a href="http://solvespace.com/forum.pl?action=viewthread&parent=1414&tt=1509142606">Simulating mechanic in V-REP</a> (Fri Oct 27 2017, 18:16:46, 7 replies)
  > ...

But if look inside topics, latest message dated on `Sat Aug 20 2016, 04:29:29`
* Latest message inside topic "Simulating mechanic in V-REP":
  > ...
  > **V-Rep is great ...** (by Roland Frank)
  > `< text of comment placed here >`
  > Sat Aug 20 2016, 04:29:29

**Comment by ruevs** [comment]
This is true for the [thread in question](https://solvespace.com/forum.pl?action=viewthread&parent=1414&tt=1509142606) but is not the case for a few recent threads I looked through as well as a few from around that time.

@phkahler @jwesthues I am closing this.
