### ISSUE TITLE
reCAPTCHA v1 will not work after March 31, 2018

### ISSUE THREAD

**Issue by ghost** [solvespace/solvespace-web#14]
Few days ago I got such reminder when try input captcha on forum
![reCAPTCHA v1](http://pasteall.org/pic/show.php?id=130742)

Short link redirect to

- https://developers.google.com/recaptcha/docs/faq#what-happens-to-recaptcha-v1

> **Any calls to the v1 API will not work after March 31, 2018**. Starting in November 2017, a percentage of reCAPTCHA v1 traffic will begin to show a notice informing users that the old API will soon be retired.
> 

As workaround its possible temporary use this
> **Does reCAPTCHA support users that don't have JavaScript enabled?**
> 
> reCAPTCHA can only provide the optimal experience in terms of security and usability with JavaScript enabled. However, if supporting users who have disabled JavaScript is important for your site, you can enable the alternative challenge with the following steps. Navigate to the admin console and move the security preference slider to "easiest for users". Keep in mind that with this setting reCAPTCHA won't be able to use all of its security features.
> ![img1](https://developers.google.com/recaptcha/images/securitypreference_easiest.png)
```html
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div class="g-recaptcha" data-sitekey="your_site_key"></div>
<noscript>
  <div>
    <div style="width: 302px; height: 422px; position: relative;">
      <div style="width: 302px; height: 422px; position: absolute;">
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=your_site_key"
                frameborder="0" scrolling="no"
                style="width: 302px; height:422px; border-style: none;">
        </iframe>
      </div>
    </div>
    <div style="width: 300px; height: 60px; border-style: none;
                   bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px;
                   background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
      <textarea id="g-recaptcha-response" name="g-recaptcha-response"
                   class="g-recaptcha-response"
                   style="width: 250px; height: 40px; border: 1px solid #c1c1c1;
                          margin: 10px 25px; padding: 0px; resize: none;" >
      </textarea>
    </div>
  </div>
</noscript>
```
> **The Invisible reCAPTCHA requires JavaScript and has no support for browsers without JavaScript enabled.**

Need look for alternative captcha provider for SolveSpace forum, especially such as reCAPTCHA v1 (noscript) now - captcha that could work without JavaScript.

**Comment by jwesthues** [comment]
Updated to reCAPTCHA v2. Let me know if anyone sees a problem.

**Comment by ghost** [comment]
> Updated to reCAPTCHA v2.

@jwesthues, Why you do that??? **No need  JavaScript-based reCAPTCHA v2 on SolveSpace forum**! 

> Let me know if anyone sees a problem.

Of course now all users that use text browser (`links2`,`w3m`, etc.) or disable JS in their browsers CAN'T use this type of captcha and post on forum anymore!
![reCAPTCHA v2](http://pasteall.org/pic/show.php?id=131410)

@jwesthues, Try use some alternative **noscript captcha** and make SolveSpace forum *independent of Google and JavaScript*!

**Comment by jwesthues** [comment]
reCAPTCHA v2 doesn't require js. I just tried it in Chrome, and it works.

**Comment by ghost** [comment]
> reCAPTCHA v2 doesn't require js.

@jwesthues, **It's not true**!

Did you read first comment with quote

- https://github.com/solvespace/solvespace-web/issues/14#issue-301868871

> **Does reCAPTCHA (i.e. reCAPTCHA v2) support users that don't have JavaScript enabled?**
> 
> reCAPTCHA (i.e. reCAPTCHA v2) can only provide the optimal experience in terms of security and usability with JavaScript enabled.  However, if supporting users who have disabled JavaScript is important for your site, you can enable the alternative challenge with the following steps. Navigate to the admin console and move the security preference slider to "easiest for users".

**Comment by jwesthues** [comment]
>  However, if supporting users who have disabled JavaScript is important for your site, you can enable the alternative challenge with the following steps. [...]

And specifically as a courtesy to you, I enabled it with those steps. You then responded with a sad-face and a thumbs-down (who at GitHub thought that was a good feature?), and a couple of unhappy comments.

This isn't a productive way to treat people who give you things for free. Let me know if the CAPTCHA doesn't work with js disabled in Chrome, Firefox, Edge, Safari, Opera, etc. I'm otherwise not going to spend more time on this.

**Comment by ghost** [comment]
> And specifically as a courtesy to you, I enabled it with those steps.

This reCAPTCHA look like depend on CSS support, but in text-only browsers (such as `links2`) there no CSS support.

I found possible way to fix this issue: just use "*noscript*" (`iframe src="https://www.google.com/recaptcha/api/fallback?k=your_site_key"`), and NOT use "fallback" (`iframe src="https://www.google.com/recaptcha/api/fallback?k=your_site_key"`).

- **Good**! (no needed nor JS, nor CSS)- https://www.google.com/recaptcha/api/noscript?k=6LchicQSAAAAAGksQmNaDZMw3aQITPqZEsX77lT9
- Bad... (need or CSS, or JS+CSS)- https://www.google.com/recaptcha/api/fallback?k=6LcDSCYTAAAAAMoBbb97LYxBVBoj8flgHNPXP9mc

**Comment by whitequark** [comment]
> in text-only browsers (such as links2) there no CSS support.

Then use a real browser instead.

**Comment by ghost** [comment]
> Then use a real browser instead.

Issue not in browser, issue with new captcha itself -- it fully suck (won't choose road signs on stupid photos, want just type few words or numbers as it was before).

@whitequark, why just not make SolveSpace's forum independent from Google's captcha? Why not make normal account registration as used on all "normal" forums? Or why not use simple self hosted Perl-based captcha such as:

- https://github.com/kappa/rcaptcha
- https://github.com/yuki-kimoto/Imager-SecurityImage/tree/master/lib/Imager
- https://github.com/OMOTO-TK/mod-captcha-for-wakaba
- https://github.com/KaiCPL/perlocaptcha

> And specifically as a courtesy to you, I enabled it with those steps.

@jwesthues, https://support.google.com/recaptcha#6262736

> **Not seeing the checkbox and want an easier challenge?**
> 
> If you're seeing this reCAPTCHA challenge, your browser environment doesn't support the reCAPTCHA checkbox widget.
> ![reCAPCTHCA JS](https://lh3.googleusercontent.com/ck2ibu4EmgPUjRRtMloWOvTzOGmoxJcYgxRHPzkmwYjbHqnARHwKwwY-C1hS1iQDlco=w286-h486)
> There are a few steps you can take to improve your experience:
> - Make sure your browser is fully updated (see minimum browser requirements)
> - Check that JavaScript is enabled in your browser
> ...

As said, reCAPTCHA V2 now require JavaScript to work

**Comment by whitequark** [comment]
Because the only one who has this problem is you, and the only thing you contribute is incessant complaints that something doesn't work in exactly the way that would be convenient to you. I am very tired of this.
