### ISSUE TITLE
demo video suggests SolveSpace isn't Free

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace-web#15]
The demo video on http://solvespace.com/index.pl begins with the following message:

*** NO LICENSE FILE IS PRESENT ***
  running as full demo, 30 days remaining
  buy at http://solvespace.com/

Fortunately, this is misleading, but might confuse visitors who don't know that SolveSpace is Free (which isn't mentioned anywhere on the front page).

**Comment by jwesthues** [comment]
I guess it's not unreasonable to reshoot the demo video once every ten years? Updated and pushed; let me know if you see any issues.

**Comment by whitequark** [comment]
Thank you!
