### ISSUE TITLE
enable HTTPS for solvespace.com

### ISSUE THREAD

**Issue by ppd** [solvespace/solvespace-web#18]
Nowadays it's good practice to enable HTTPS for the following reasons:

- user data protection for forms or any queries in general (forum?)
- users feel more confident if they don't see a crossed out lock/warning (depends on browser)
- SEO (some crawlers rank HTTPS higher)
- No injections of adware by malicious ISPs possible

~Implementation-wise, it's become almost trivial to set up at no (monetary) cost via [certbot](https://certbot.eff.org/)/[letsencrypt](https://letsencrypt.org/).~

I can see that this is hosted on GH pages, correct? Then it's even easier to set up: https://github.blog/2018-05-01-github-pages-custom-domains-https/

**Comment by jwesthues** [comment]
It's hosted on my little VPS, behind Cloudflare. https did actually work before, but there was a stupid redirect that always sent `solvespace.com/` to `http://solvespace.com/index.pl`, even if the original request was https. So few people ever got https, unless they actually typed in `https://solvespace.com/page.pl`.

I've fixed that and made http always redirect to https, in 936c01e908c390208f0fb6735d3fce3ac76ff439 plus some apache2.conf changes that aren't checked in. As before, `www.solvespace.com` will also redirect to `solvespace.com`. Please confirm all looks right, and close or advise.

**Comment by ppd** [comment]
It looks fine now :+1:
