### ISSUE TITLE
User Showcases / Example Files

### ISSUE THREAD

**Issue by BPLRFE** [solvespace/solvespace-web#2]
Would be great if users could upload/contribute with screenshots and files of cool projects

**Comment by whitequark** [comment]
I'm not sure how much interest there is. Perhaps start a forum thread first? There's already an upload feature, so no additional development is needed. Then if it gets great submissions we can publish them on the main website.

Closing for now but feel free to comment here once the thread has a few submissions worth showcasing and I'll figure something out.
