### ISSUE TITLE
Add a section on using styles for solids in the reference

### ISSUE THREAD

**Issue by ruevs** [solvespace/solvespace-web#22]
The re is a [section on "Line Styles" in the reference](https://solvespace.com/ref.pl) and styles usage is described in a few more relevant places. But a section on applying styles to solids would be useful.
https://github.com/solvespace/solvespace/issues/890#issuecomment-762291761

**Comment by robnee** [comment]
I should probably take a look at this since I've been knee-deep in the styling code recently.

**Comment by ruevs** [comment]
That would be great!
