### ISSUE TITLE
Some forum links are broken (was Make http -> https redirects to the forum work)

### ISSUE THREAD

**Issue by ruevs** [solvespace/solvespace-web#29]
If one visits an existing `http` link to a forum thread it redirects to `https://solvespace.com/index.pl`. It should instead redirect to the proper `https` URL in the forum.

For example ([taken from here](https://github.com/solvespace/solvespace/issues/245#issuecomment-297767048)):

http://solvespace.com/forum?action=viewthread&parent=872

Should redirect to:

https://solvespace.com/forum.pl?action=viewthread&parent=872

@jwesthues I think you are the only one who can fix this.

**Comment by jwesthues** [comment]
The problem seems to be `forum?...` instead of `forum.pl?...`, not the http, since

http://solvespace.com/forum.pl?action=viewthread&parent=872

works as expected. Do you have any more examples of that? If it's systematic then I could add a redirect.

**Comment by ruevs** [comment]
Oh you are right, I did not notice... OK, very few that I can find:
https://github.com/solvespace/solvespace/issues/245#issuecomment-297767048

It seems Google knows of only nine :-)

https://www.google.com/search?q=%22solvespace.com/forum?action%3D%22

 And still very few with "similar" shown

https://www.google.com/search?q=%22solvespace.com/forum?action%3D%22&filter=0


I'll close this :-)
