### ISSUE TITLE
Update "Features" with changes between 2.0..2.3

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace-web#3]
Unresolved questions: should we mention the version number in every line? Or should we just copy `features.pl` to, say, `features-2.0.pl`, and add a selector? It seems odd to remove the documentation for old versions forever.

**Comment by BPLRFE** [comment]
The features present in 2.0 would need no tag.
But with newer features you could add something like (since 2.3) or similar ...

**Comment by ruevs** [comment]
https://github.com/solvespace/solvespace-web/pull/20
