### ISSUE TITLE
Document dimensions input math evaluation

### ISSUE THREAD

**Issue by hinell** [solvespace/solvespace-web#33]
Add documentation for the said feature.
### Related
* [#issuecomment-1032485216](../../solvespace/issues/1211#issuecomment-1032485216)
* https://github.com/solvespace/solvespace/issues/1211 issue.

### Dimension input field
It's possible to evaluate basic math expressions in place by using standard number operators and some functions:
##### Functions
* `sqrt`
* `square`
* `sin`, `cos`, `asin`,`acos`
* `pi`
##### Operators
 `+`, `-`, `*`, `/`, `()`

<details>
<summary>Source code</summary>

```
`sqrt`
`square`
`sin`, `cos`, `asin`,`acos`
`pi`
 `+`, `-`, `*`, `/`, `()`
```

</details>

**Comment by ruevs** [comment]
There is a bit of documentation [here](https://solvespace.com/ref.pl):

> ### Dimension Entry and Units
> All dimensions are entered in the current display units. In most places where a dimension is expected, it's possible to enter an arithmetic expression ("4*20 + 7") instead of a single number. 

But adding the supported operations is a good idea.
