### ISSUE TITLE
Ability to calculate dimensions and angles from input variables

### ISSUE THREAD

**Issue by simonwibberley** [solvespace/solvespace-web#41]
It'd be extremely useful to allow a set of input variables which can be reference in the calculation of other parameters. 

I suppose the general case is to allow functions over constraints, however I imagine that would up to the solver.

But would it be possible to allow a set of variables and functions to define input numbers on which other  constructs could be based? 

Apologies if this is already possible! I couldn't figure out how,

Thanks!

**Comment by ruevs** [comment]
This is the project for the website of SolveSpace.

The project for SolveSpace itself is here:
https://github.com/solvespace/solvespace/issues and issues related to it should be created there.

What you are asking for is currently not possible. Here is the issue tracking it https://github.com/solvespace/solvespace/issues/77

Please refer to the pinned issue https://github.com/solvespace/solvespace/issues/1024 for more information.
