### ISSUE TITLE
Website Rework Proposal

### ISSUE THREAD

**Issue by Draconis-25** [solvespace/solvespace-web#42]
As the current website is outdated, me and my friend @PreA1pha has created a rework plan to make it more usable.
The current website has the following pages which can be moved to:
- Examples -> /examples
- Tutorials -> docs.solvespace.com
- Reference -> docs.solvespace.com
- Features -> /features
- Download -> /download
- Technology -> docs.solvespace.com
- Library -> docs.solvespace.com
- Forum -> forum.solvespace.com 
- Contact -> /community

The old page can be moved to old.solvespace.com.

The new website can be examined under 3 parts: technology, structure, and styling. In this message, only the first two will be addressed. Also the design of the forum is to be shared at a later time.

### Technologies: 

The new page would use Python with [Bottle](https://bottlepy.org/docs/dev/) to keep it minimal yet functional, using as little Javascript as possible. For the storage of forum threads, SQLite databases would be used.
The Docs page and the tutorials would use  [mdBook](https://github.com/rust-lang/mdBook/) to provide simplicity, ease of writing, and navigation.

#### Header:
Pretty basic header as a navbar:
`| Logo | Title | —--------- | Docs | Features | Examples | Community | Download |`
#### 1. Index (/):

We switch the video for a screenshot and take the parametric cad text from the header to the landing page.  There will be download and docs buttons. (For reference, lunar vim website)

Right under that, there will be three feature highlights with the following points:
- Lightweight,
- Easy to Use,
- Free & open source.

In the third section, there will be the demo video, followed by a few images, then a standard footer with navigation and social links.

#### 2. Docs(/docs):
solvespace.com/docs will redirect to  docs.solvespace.com which will include a [mdBook](https://github.com/rust-lang/mdBook/releases) book. 

#### Features, examples, community, download:
Standard designs for features, a grid of photos for examples, and a list of un/official social links for the community.
The download page would include the changelog and an older version browser.

## Questions:

1.  Is the hosting service capable of running Python?
2. Is there anything that would prevent us from using subdomains? 

## Needs:

1. Two new branches to this repository:
    - Dev, so that we will have a place other than a fork to push
    - Old, to host the current version of the website
2. A list of all related communities, whether it's official or not.
3. Feedback.

**Comment by ruevs** [comment]
My feedback is, that the website is SolveSpace's least significant problem. In fact I like web sites that "never" change. The current one has all the available information easily accessible and works just fine. It is trivial to maintain/update.

As far as I am aware there are no "web developers" among the contributors so "complications" will not be (well/easily/eagerly) maintained.

**Comment by Draconis-25** [comment]
Even if it's the least significant problem, it's still a problem. I like this piece of software, both I and my friend have experience in web development. With the website, we propose,  the website would look and feel better. Also, the parts that would need to change in time would be the docs. By using mdBook, the docs would be written in Markdown, which should be easier than the current version.

And well, I'm thinking of sticking here for a while, getting rid of the complications that may arise. Even if all fails, the old website is always available, so I don't think that there is a reason why we should not try. All the extra work that would be done by contributors (except for me and my friend) would be to give us a chance, a branch, check and merge once in a while.

**Comment by ruevs** [comment]
This was just my opinion, and I'm not the maintainer. @phkahler is and @jwesthues created and hosts the site.

As for a branch to work on - you could just make one on your fork.

**Comment by Draconis-25** [comment]
Created the following landing page for the proposal:

![image](https://github.com/solvespace/solvespace-web/assets/66898768/3e778c5f-5ff0-405e-9dcf-1888c3f70799)

**Comment by phkahler** [comment]
Ugh, I hate when these more subjective issues come up ;-)  So my opinion on a bunch of things:

I like the fact that the site is mostly static.  Related: Just noticed that when I go to solvespace.com the URL indicates I'm viewing .pl files. I thought it was supposed to convert them all to .html  -  what's up with that?

I don't see the need to change the web site infrastructure, but maybe markdown would be a better source format for all the documentation. I would like a little nicer looking landing page, but not at the expense of complexity.

Not sure why a header is better than a nav menu on the left. Screens are wide these days. Also I really hate the trend of having 3 (or more) panels advertising features. In the image above it says Open Source right under SolveSpace, so that panel is redundant. The download button is also redundant given the same thing in the header.  Easy to use seems like a good thing to let people know about ;-)

The documentation should be output to html, and IMHO we should offer an option to download the docs which means they need to be readable locally without anything other than a web browser.

I do like the dark background a lot and it goes well with the look of solvespace itself. The font / text above the download button in the image is really nice. Please tell me its not a custom font, because we aren't going there ;-)

Not a fan of creating branches on this repository. Working on a fork is not a burden, it's how github is meant to be used.

So IMHO some improvements are overdue, but not sure what parts of this proposal to keep and what not to. Can some of the layout and general appearance be changed within the existing tooling? That is much easier to evaluate.

**Comment by Draconis-25** [comment]
> I like the fact that the site is mostly static. 

The proposal uses Python for two reasons only, and it's pretty much a static page aside from those. One is the forum, which does need to be dynamic, and the second is routing, which doesn't need to be. However, we already need to use some form of dynamic features so, why not do it that way too?

> I would like a little nicer-looking landing page, but not at the expense of complexity.

The landing page you see in my image is not more complex than the current one, it's basic HTML & CSS, which I can say with confidence. Actually, I can guarantee that most of the website will be even simpler, if not as simple (excluding the forum, which I don't know yet)

> Not sure why a header is better than a nav menu on the left.

The reason why I went with a header is that we can add a sidebar on pages that need it like the examples and the forum, without mixing the content of the two.

> Also I really hate the trend of having 3 (or more) panels advertising features. In the image above it says Open Source right under SolveSpace, so that panel is redundant. The download button is also redundant given the same thing in the header. Easy to use seems like a good thing to let people know about ;-)

That, I also don't like. It's just there because it's pretty common nowadays and I'd be more than happy to remove that and add something more useful like a small introduction paragraph or etc. The download button serves on the header for, well, navigation but the one on the landing page is to pursue the visitors slowly into checking it out. There is some psychology involved, and I think it's nice to have.

My proposal for the documentation is to use [mdBook](https://rust-lang.github.io/mdBook/). It takes Markdown files as input and builds them into HTML pages, with 5 built-in themes and search functionality out of the box. It also does have a plugin that allows .pdf outputs, yet I have not used that myself.

The fonts that are used in the website are Montserrat (titles) and Lato, both are licensed under the SIL Open Font License.

> So IMHO some improvements are overdue, but not sure what parts of this proposal to keep and what not to. Can some of the layout and general appearance be changed within the existing tooling? That is much easier to evaluate.

The landing page I've posted is a complete rewrite as it's just easier to make a new one. When it's like this, there is no reason to keep the existing tooling as it's mostly HTML, just being rewritten, and PERL, which to be honest, I don't think is a good option for web development. Python is just easier to maintain and develop.

And about what to keep part, I'll share everything that I do and we can talk about them, check what works and what doesn't. It's my belief that the end result will be satisfactory for most.

**Comment by Draconis-25** [comment]
Though it needs some polish, this is the features page I came up with:

![image](https://github.com/solvespace/solvespace-web/assets/66898768/be882202-a009-4c2f-9c95-b7c8b74cd37a)

**Comment by Draconis-25** [comment]
And this makes the downloads page:
![image](https://github.com/solvespace/solvespace-web/assets/66898768/8a2fafb6-f7cb-44ef-b583-c5c089b95bb3)

**Comment by ruevs** [comment]
> And this makes the downloads page:

At least for me such a download page is a BIG step back compared to current one. The current one gives at a single glance:
- What versions are available.
- For which platforms.
- How to install it (and even a link how to build it).
- What the recent changes are (a link).
- How to report bugs (a link).
- A short note on backward compatibility of models.
- And a short crash course on how to use it.

The proposed one has:
- The latest version
- The three platforms

Presumably the "Instructions & Help" button hides the rest of the information. Personally I HATE this approach. Things are made to look "slick/simple/clean/streamlined" by actually hiding useful information and forcing one to look for it. Typical example - Firefox download page - and most other "user" software.

SolveSpace is NOT "user" software. This https://www.virtualbox.org/wiki/Downloads is a good download page for a technical person - and presumably SolveSpace users (even though perhaps mechanical engineers) are technical users.

**Comment by Draconis-25** [comment]
I would have to disagree. Let's compare what are included in the mentioned websites.

| Current Solvespace          | Virtualbox         | Proposal             |
| --------------------------- | ------------------ | -------------------- |
| Available Versions          | -                  | -                    |
| Supported Platforms         | +                  | +                    |
| How to install              | -                  | linked               |
| CHANGELOG(link)             | linked             | -                    |
| Reporting bugs(link)        | -                  | -                    |
| Backwards comp. notice      | -                  | -                    |
| User guide                  | link to the manual | link to the tutorial |
| Build instructions   (link) | linked             | -                    |

Thus, if I were to say that the proposal is closer to the virtualbox website, that would not be a lie. However there are some extras in the thereof website:

| VBox              | Solvespace    |
| ----------------- | ------------- |
| Checksums         | doesn't exist |
| Related doenloads | doesn't exist |
| FAQ (link)        | doesn't exist |
| Source Code       | Github        |

Putting aside the nonexistent stuff, one may wonder why I've written source code in the extras. The reason is that they host their downloads in their website, whereas solvespace uses GitHub.

Now, bearing in mind that Solvespace is not "user" software, let's check the differences that are:

## Changelog & Backwards Compatibility Notice
As solvespace targets experienced users, it's safe to assume that they know the place in which this data is stored, is GitHub releases. Therefore, such section is redundant in the downloads page.

Reference:
1. [Rust](https://github.com/rust-lang/rust/releases/tag/1.71.0)
2. [V](https://github.com/vlang/v/releases/tag/0.4)
3. [neoVim](https://github.com/neovim/neovim/releases/tag/stable)
4. [LibrePCB](https://github.com/LibrePCB/LibrePCB/releases/tag/0.1.7)
5. [ImGUI](https://github.com/ocornut/imgui/releases/tag/v1.89.8)
6. [Godot Engine](https://github.com/godotengine/godot/releases/tag/4.1.1-stable)
7. and many more.

## Build Instructions & Installation Guide
Similarly to the previous section, an experienced user would seek the such instructions in either README.md or in the documentation. Even more experienced, wouldn't even seek it.

Reference: All previous references apply.

That leaves us with:

| Current Solvespace          | Virtualbox         | Proposal             |
| --------------------------- | ------------------ | -------------------- |
| Available Versions          | -                  | -                    |
| Reporting bugs(link)        | -                  | -                    |
| User guide                  | link to the manual | link to the tutorial |

Both the versions and the issues of solvespace are hosted in GitHub and one doesn't need to be experienced to use and find those. Which makes it better to put them inside the documentation, who's sole purpose is to provide answers.

And the user guide in the downloads page is nowhere near being enough for a beginner, who should check the tutorial instead. For experienced people let me speak from experience. I have no experience in CAD. I have used Cinema 4D in the past but my main experience is in game development. It took me about 5 minutes to figure out everything that is written in the tutorial and again, I have no CAD experience whatsoever. 

I believe that these are reasonable enough to justify the proposed website.

**Comment by phkahler** [comment]
> Though it needs some polish, this is the features page I came up with:

Just no. That's not a features page, and it's terrible design. Also, we are not changing the way the website is managed and deployed. The end. It's not really open for debate.

> As solvespace targets experienced users, it's safe to assume that they know the place in which this data is stored, is GitHub releases. Therefore, such section is redundant in the downloads page.

Again, No. Most Solvespace users have little in common with people who use Rust, NeoVim, ImGUI or any of that.  Isn't that like the first rule of good design, to know your audience?

> I have no experience in CAD. I have used Cinema 4D in the past but my main experience is in game development. It took me about 5 minutes to figure out everything that is written in the tutorial and again, I have no CAD experience whatsoever.

So it works great just the way it is.

**Comment by Draconis-25** [comment]
Though I do not agree, it's your project, your decision. I wish for a good future for this project. Due to my education, I won't be able to work on many projects for about two years. Until then keep up the good work, keep it alive.
