### ISSUE TITLE
Update "Reference" with every new feature added since 2.0

### ISSUE THREAD

**Issue by whitequark** [solvespace/solvespace-web#5]

**Comment by BPLRFE** [comment]
If i understand correct, something like a changelog is needed ?
Stating
2.0 - initial release with GPL-license
2.3
- improved this
- added that

**Comment by whitequark** [comment]
Here is the changelog: https://github.com/solvespace/solvespace/blob/master/CHANGELOG.md#21

**Comment by ruevs** [comment]
https://github.com/solvespace/solvespace-web/pull/17
https://github.com/solvespace/solvespace-web/pull/20
