### ISSUE TITLE
Solvespace and social media

### ISSUE THREAD

**Issue by BPLRFE** [solvespace/solvespace-web#7]
Since i noticed that @whitequark already has a reddit-account, maybe creating a sub-reddit
for solvespace would be a good idea ?
If there would be one, there could be a link on the front page of the solvespace Homepage ?

If some news/announcements were posted there, this would help spread the word about the program ...

**Comment by whitequark** [comment]
Would a subreddit have any benefit? It's functionally very similar to our existing forum, and that would just disperse information between these two resources, and make it harder to find.

We should add a link to IRC, sure.

**Comment by ruevs** [comment]
@phkahler closing this since [Whitequark is not involved any more](https://github.com/solvespace/solvespace/issues/714).

**Comment by phkahler** [comment]
There is also a reddit, but it gets very little traffic.
