### ISSUE TITLE
Add a page "Contribute"

### ISSUE THREAD

**Issue by BPLRFE** [solvespace/solvespace-web#8]
Add a "Contribute" page explaining
- Why Paypal donations would make no sense at the moment
- Users can do pull requests with the source code on github
- Users can do pull requests with the homepage on github
- Users can do video tutorials (on youtube or similar)
- Users can do  written tutorials (and submit them via the forum)
- Users can publish e-books via wikibooks or gitbooks or similar
- Users can write in the forum
- Users can write bug-reports
- Users can showcase Solvespace-Projects (for example on GrabCAD or Thingiverse or in the forum)

**Comment by ruevs** [comment]
But wouldn't users who can and want to do these things already know (or be able to discover) that they can do them?
In my opinion such a page is superfluous.

**Comment by phkahler** [comment]
There's a contribute section on the github page. Maybe just a link to that?

**Comment by ruevs** [comment]
Again - woudn't anyone qualified to use [CONTRIBUTING.md](https://github.com/solvespace/solvespace/blob/master/CONTRIBUTING.md) be able to find it?
