### ISSUE TITLE
Add a page "Rendering"

### ISSUE THREAD

**Issue by BPLRFE** [solvespace/solvespace-web#9]
I would add a page for export tipps for rendering models.
Since Solvespace is GPL I would post tips for export to free/open source renderers like
> POVRay (http://povray.org/)
> Kerkythea (http://www.kerkythea.net/cms/)
> Cadrays (https://www.opencascade.com/content/cadrays)
> WebGL Raytracer (http://webraytracer.alexandra.dk/#)

**Comment by whitequark** [comment]
I have never heard of anyone rendering models created using SolveSpace, usually people export them for CAM.

**Comment by ghost** [comment]
@BPLRFE, what about next:

* Blender / Cycles ( http://blender.org )
  * https://docs.blender.org/manual/en/dev/render/cycles/introduction.html
  * https://github.com/eLeDeTe-LoDeTanda/RCL-RenderCommandLine-
    * https://github.com/eLeDeTe-LoDeTanda/Brenders
* Radeon ProRender ( https://github.com/Radeon-ProRender )
  * https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal
* LuxRender ( http://luxrender.net )
  * https://www.blendernation.com/2017/08/07/introduction-luxrender-tutorial/
* YafaRay ( https://github.com/YafaRay/ )
  * http://www.yafaray.org/community/forum/viewtopic.php?f=15&t=5249#p32111

**REFERENCE**:

* https://github.com/leozide/leocad/issues/70

**Comment by BPLRFE** [comment]
Basically yes. I wrote "I would post tipps ..." because I have (sometimes little) experience with the renderers I mentioned.
Kerkythea and WebGL would accept OBJ, CadRays would accept Step and OBJ.
POV-Ray would mean converting with Meshlab (haven't tested yet) from OBJ/STL to POV.

@whitequark: I understand that you are hesitant to cluster the homepage with information.
What about creating Solvespace books for different subjects for example on Wikibooks ?

**Comment by whitequark** [comment]
@BPLRFE I'm really happy to add information to solvespace.com so long as it's correct, relevant and well-written. E.g. a list of links to renderers doesn't qualify but a short tutorial for each one would be extremely nice.

If you open a pull request, we can iterate there and then I'll merge once it looks finished. Sounds good?

**Comment by ghost** [comment]
As for me, Blender should be "recommended" software for postprocessing 3D mesh models exported from SolveSpace.

As advantage, Blender has few own renders and support near all listed above renders. Also it has big number of free tutorials and very friendly community that could help if somebody decide to edit, animate and render mesh models exported from SolveSpace.

As for SolveSpace website/tutorial "postprocessing" is little out of scope thing. Main target for official tutorial should be tips on use SolveSpace for 2D and 3D CAD design.

**Comment by ruevs** [comment]
In my opinion this is not a necessary part for solvespace.com.
Anyone who has discovered SolveSpace and knows how to use some "rendering" software will know what to do and will not need an explanation.
The export capabilities of SolveSpace are documented in the "Export section in the reference manual.

@phkahler should I close this?

**Comment by phkahler** [comment]
@ruevs. Yes, it's our place to explain how to export to different formats, not to explain all the options people might use beyond that.
